apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "books-api.fullname" . }}
  labels:
    {{- include "books-api.labels" . | nindent 4 }}
data:
  # Add any configuration data here
  # Example:
  # app.config: |
  #   key: value
